name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          render_service_id: your_render_service_id
          render_api_key: ${{ secrets.RENDER_API_KEY }}
